layout : disqus
disqus :
  short_name : jekyllbootstrap # Change This!
livefyre :
  site_id : 123
  site_name:
intensedebate :
  account : 123abc
facebook :
  appid : 123
  num_posts: 5
  width: 580
  colorscheme: light
